<?php
return [
    'types' => [
        'body' => ['label' => 'متن' ,'type' => 'editor'],
        'rightImage' => ['label' => 'تصویر سمت راست' ,'type' => 'file'],
        'leftImage' => ['label' => 'تصویر سمت چپ' ,'type' => 'file'],
        'centerImage' => ['label' => 'تصویر وسط' ,'type' => 'file'],
        'video' => ['label' => 'ویدیو' ,'type' => 'file'],
        'poster' => ['label' => 'پوستر' ,'type' => 'file'],
        'downText' => ['label' => 'متن' ,'type' => 'text'],
        'subtitle' => ['label' => 'زیرعنوان' ,'type' => 'text'],
        'about' => ['label' => 'درباره' ,'type' => 'json'],
        'btn1' => ['label' => 'دکمه اول' ,'type' => 'json'],
        'btn2' => ['label' => 'دکمه اول' ,'type' => 'json'],
        'service' => ['label' => 'خدمات' ,'type' => 'json'],
        'buttons' => ['label' => 'دکمه ها' ,'type' => 'array'],
        'tabs' => ['label' => 'تب ها' ,'type' => 'array'],
        'tab_contents' => ['label' => 'تب ها' ,'type' => 'array'],
        'title' => ['label' => 'عنوان' ,'type' => 'text'],
        'titleEn' => ['label' => 'عنوان لاتین' ,'type' => 'text'],
        'class' => ['label' => 'کلاس' ,'type' => 'text'],
        'icon' => ['label' => 'آیکون' ,'type' => 'textarea'],
        'text' => ['label' => 'متن' ,'type' => 'textarea'],
        'link' => ['label' => 'لینک' ,'type' => 'text'],
        'limit' => ['label' => 'تعداد محدود' ,'type' => 'text'],
        'show' => ['label' => 'نمایش' ,'type' => 'boolean'],
        'paginate' => ['label' => 'صفحه بندی' ,'type' => 'boolean'],
        'perPage' => ['label' => 'تعداد نمایش در هر صفحه' ,'type' => 'text'],
        'filter' => ['label' => 'فیلتر' ,'type' => 'boolean'],
        'home' => ['label' => 'حالت نمایش در صفحه اصلی' ,'type' => 'boolean'],
        'slider' => ['label' => 'اسلایدر' ,'type' => 'boolean'],
        'frame' => ['label' => 'کد embed' ,'type' => 'textarea'],
        'url' => ['label' => 'تصویر|ویدیو' ,'type' => 'file'],
        'address' => ['label' => 'آدرس' ,'type' => 'textarea'],
        'email' => ['label' => 'ایمیل' ,'type' => 'text'],
        'phone' => ['label' => 'شماره' ,'type' => 'text'],
        'workingHours' => ['label' => 'ساعات کار' ,'type' => 'text'],
        'socialMedia1' => ['label' => 'شبکه اجتماعی 1' ,'type' => 'text'],
        'socialMedia2' => ['label' => 'شبکه اجتماعی 2' ,'type' => 'text'],
        'socialMedia3' => ['label' => 'شبکه اجتماعی 3' ,'type' => 'text'],
        'form' => ['label' => 'فرم تماس' ,'type' => 'select' , "model" => ""],
        'categoryAcademyIds' => ['label' => 'دسته بندی' ,'type' => 'multiSelect' , "model" => "App\\Models\\Category"  , "cat_type" => 2],
        'categoryPostIds' => ['label' => 'دسته بندی' ,'type' => 'multiSelect' , "model" => "App\\Models\\Category"  , "cat_type" => 1],
    ],
    'masters' => [
        array('title' => 'اصلی', 'loc' => 'layouts.app'),
        array('title' => 'صفحه داخلی', 'loc' => 'layouts.inner-app')
    ]
];
